import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'en',
        'es',
        'zh_Hans',
        'hi',
        'bn',
        'pt',
        'ru',
        'ja',
        'de',
        'ko',
        'fr',
        'ta',
        'te',
        'mr',
        'kn',
        'ro'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? zh_HansText = '',
    String? hiText = '',
    String? bnText = '',
    String? ptText = '',
    String? ruText = '',
    String? jaText = '',
    String? deText = '',
    String? koText = '',
    String? frText = '',
    String? taText = '',
    String? teText = '',
    String? mrText = '',
    String? knText = '',
    String? roText = '',
  }) =>
      [
        enText,
        esText,
        zh_HansText,
        hiText,
        bnText,
        ptText,
        ruText,
        jaText,
        deText,
        koText,
        frText,
        taText,
        teText,
        mrText,
        knText,
        roText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // SignUp
  {
    'hxoppopu': {
      'en': 'Sign up',
      'bn': 'সাইন আপ করুন',
      'de': 'Melden Sie sich an',
      'es': 'Inscribirse',
      'fr': 'S\'inscrire',
      'hi': 'साइन अप करें',
      'ja': 'サインアップ',
      'kn': 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
      'ko': '가입하기',
      'mr': 'साइन अप करा',
      'pt': 'Inscrever-se',
      'ro': 'Înscrie-te',
      'ru': 'Зарегистрироваться',
      'ta': 'பதிவு செய்யவும்',
      'te': 'సైన్ అప్ చేయండి',
      'zh_Hans': '报名',
    },
    'qz9d2aiu': {
      'en': 'Hello there 👋 Please enter your details.',
      'bn': 'নমস্কার 👋 অনুগ্রহ করে আপনার বিবরণ লিখুন।',
      'de': 'Hallo 👋 Bitte geben Sie Ihre Daten ein.',
      'es': 'Hola 👋 Por favor ingrese sus datos.',
      'fr': 'Bonjour 👋 Veuillez saisir vos coordonnées.',
      'hi': 'नमस्ते 👋 कृपया अपना विवरण दर्ज करें।',
      'ja': 'こんにちは👋 詳細を入力してください。',
      'kn': 'ನಮಸ್ಕಾರ 👋 ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
      'ko': '안녕하세요 👋 자세한 내용을 입력해 주세요.',
      'mr': 'नमस्कार 👋 कृपया तुमची माहिती प्रविष्ट करा.',
      'pt': 'Olá 👋 Por favor, insira seus dados.',
      'ro': 'Salut 👋 Te rugăm să introduci datele tale.',
      'ru': 'Здравствуйте 👋 Введите свои данные.',
      'ta': 'வணக்கம் 👋 உங்கள் விவரங்களை உள்ளிடவும்.',
      'te': 'హలో 👋 దయచేసి మీ వివరాలను నమోదు చేయండి.',
      'zh_Hans': '你好👋请输入您的详细信息。',
    },
    '6yf8iar4': {
      'en': 'Name',
      'bn': 'নাম',
      'de': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'hi': 'नाम',
      'ja': '名前',
      'kn': 'ಹೆಸರು',
      'ko': '이름',
      'mr': 'नाव',
      'pt': 'Nome',
      'ro': 'Nume',
      'ru': 'Имя',
      'ta': 'பெயர்',
      'te': 'పేరు',
      'zh_Hans': '姓名',
    },
    'xx7985g1': {
      'en': 'Enter your name',
      'bn': 'তোমার নাম লিখ।',
      'de': 'Geben Sie Ihren Namen ein',
      'es': 'Introduce tu nombre',
      'fr': 'Entrez votre nom',
      'hi': 'अपना नाम दर्ज करें',
      'ja': '名前を入力してください',
      'kn': 'ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'ko': '이름을 입력하세요',
      'mr': 'तुमचे नाव एंटर करा',
      'pt': 'Digite seu nome',
      'ro': 'Introduceți numele dvs.',
      'ru': 'Введите свое имя',
      'ta': 'உங்கள் பெயரை உள்ளிடவும்',
      'te': 'మీ పేరును నమోదు చేయండి',
      'zh_Hans': '输入您的姓名',
    },
    'k45cn5yv': {
      'en': 'Email',
      'bn': 'ইমেইল',
      'de': 'E-Mail',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'ja': 'メール',
      'kn': 'ಇಮೇಲ್',
      'ko': '이메일',
      'mr': 'ईमेल',
      'pt': 'E-mail',
      'ro': 'E-mail',
      'ru': 'Электронная почта',
      'ta': 'மின்னஞ்சல்',
      'te': 'ఇ-మెయిల్',
      'zh_Hans': '电子邮件',
    },
    'yfu4tl8t': {
      'en': 'Enter your email',
      'bn': 'আপনার ইমেল লিখুন',
      'de': 'Geben Sie Ihre E-Mail ein',
      'es': 'Introduce tu correo electrónico',
      'fr': 'Entrez votre email',
      'hi': 'अपना ईमेल दर्ज करें',
      'ja': 'メールアドレスを入力してください',
      'kn': 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
      'ko': '이메일을 입력하세요',
      'mr': 'तुमचा ईमेल एंटर करा',
      'pt': 'Digite seu e-mail',
      'ro': 'Introdu adresa ta de e-mail',
      'ru': 'Введите свой адрес электронной почты',
      'ta': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
      'te': 'మీ ఇమెయిల్‌ను నమోదు చేయండి',
      'zh_Hans': '输入您的电子邮件',
    },
    'pltgg8o4': {
      'en': 'Password',
      'bn': 'পাসওয়ার্ড',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'ja': 'パスワード',
      'kn': 'ಪಾಸ್ವರ್ಡ್',
      'ko': '비밀번호',
      'mr': 'पासवर्ड',
      'pt': 'Senha',
      'ro': 'Parolă',
      'ru': 'Пароль',
      'ta': 'கடவுச்சொல்',
      'te': 'పాస్‌వర్డ్',
      'zh_Hans': '密码',
    },
    '82ef0k0x': {
      'en': '••••••••',
      'bn': '••••••••',
      'de': '••••••••',
      'es': '••••••••',
      'fr': '••••••••',
      'hi': '••••••••',
      'ja': '••••••••',
      'kn': '•••••••••',
      'ko': '••••••••',
      'mr': '••••••••',
      'pt': '••••••••',
      'ro': '•••••••••',
      'ru': '••••••••',
      'ta': '•••••••••',
      'te': '•••••••••',
      'zh_Hans': '••••••••',
    },
    'yzeetrkh': {
      'en': 'Confirm Password',
      'bn': 'পাসওয়ার্ড নিশ্চিত করুন',
      'de': 'Passwort bestätigen',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'hi': 'पासवर्ड की पुष्टि कीजिये',
      'ja': 'パスワードを認証する',
      'kn': 'ಪಾಸ್‌ವರ್ಡ್ ಅನ್ನು ದೃಢೀಕರಿಸಿ',
      'ko': '비밀번호 확인',
      'mr': 'पासवर्डची पुष्टी करा',
      'pt': 'Confirme sua senha',
      'ro': 'Confirmați parola',
      'ru': 'Подтвердите пароль',
      'ta': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'te': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
      'zh_Hans': '确认密码',
    },
    'vj7ql2p4': {
      'en': '••••••••',
      'bn': '••••••••',
      'de': '••••••••',
      'es': '••••••••',
      'fr': '••••••••',
      'hi': '••••••••',
      'ja': '••••••••',
      'kn': '•••••••••',
      'ko': '••••••••',
      'mr': '••••••••',
      'pt': '••••••••',
      'ro': '•••••••••',
      'ru': '••••••••',
      'ta': '•••••••••',
      'te': '•••••••••',
      'zh_Hans': '••••••••',
    },
    'ees81j79': {
      'en': 'Email is required.',
      'bn': 'ইমেল প্রয়োজন।',
      'de': 'E-Mail ist erforderlich.',
      'es': 'Se requiere correo electrónico.',
      'fr': 'L\'e-mail est obligatoire.',
      'hi': 'ईमेल की जरूरत है।',
      'ja': 'メールアドレスは必須です。',
      'kn': 'ಇಮೇಲ್ ಅಗತ್ಯವಿದೆ.',
      'ko': '이메일은 필수입니다.',
      'mr': 'ईमेल आवश्यक आहे.',
      'pt': 'E-mail é obrigatório.',
      'ro': 'Este obligatorie adresa de e-mail.',
      'ru': 'Требуется адрес электронной почты.',
      'ta': 'மின்னஞ்சல் தேவை.',
      'te': 'ఇమెయిల్ అవసరం.',
      'zh_Hans': '需要电子邮件。',
    },
    'jc2e3hyr': {
      'en': 'Please choose an option from the dropdown',
      'bn': 'ড্রপডাউন থেকে একটি বিকল্প বেছে নিন।',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste',
      'es': 'Por favor, elija una opción del menú desplegable.',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'hi': 'कृपया ड्रॉपडाउन से कोई विकल्प चुनें',
      'ja': 'ドロップダウンからオプションを選択してください',
      'kn': 'ದಯವಿಟ್ಟು ಡ್ರಾಪ್‌ಡೌನ್‌ನಿಂದ ಒಂದು ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ.',
      'ko': '드롭다운에서 옵션을 선택하세요',
      'mr': 'कृपया ड्रॉपडाउनमधून एक पर्याय निवडा.',
      'pt': 'Por favor, escolha uma opção no menu suspenso',
      'ro': 'Vă rugăm să alegeți o opțiune din meniul derulant',
      'ru': 'Пожалуйста, выберите вариант из выпадающего списка',
      'ta':
          'கீழ்தோன்றும் பட்டியலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்.',
      'te': 'దయచేసి డ్రాప్‌డౌన్ నుండి ఒక ఎంపికను ఎంచుకోండి.',
      'zh_Hans': '请从下拉菜单中选择一个选项',
    },
    'hdnre5wj': {
      'en': 'Password is required.',
      'bn': 'পাসওয়ার্ড প্রয়োজন।',
      'de': 'Passwort ist erforderlich.',
      'es': 'Se requiere contraseña.',
      'fr': 'Le mot de passe est requis.',
      'hi': 'पासवर्ड आवश्यक है.',
      'ja': 'パスワードが必要です。',
      'kn': 'ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯವಿದೆ.',
      'ko': '비밀번호가 필요합니다.',
      'mr': 'पासवर्ड आवश्यक आहे.',
      'pt': 'É necessária uma senha.',
      'ro': 'Este necesară o parolă.',
      'ru': 'Требуется пароль.',
      'ta': 'கடவுச்சொல் தேவை.',
      'te': 'పాస్‌వర్డ్ అవసరం.',
      'zh_Hans': '需要密码。',
    },
    'dze5zejr': {
      'en': 'Please choose an option from the dropdown',
      'bn': 'ড্রপডাউন থেকে একটি বিকল্প বেছে নিন।',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste',
      'es': 'Por favor, elija una opción del menú desplegable.',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'hi': 'कृपया ड्रॉपडाउन से कोई विकल्प चुनें',
      'ja': 'ドロップダウンからオプションを選択してください',
      'kn': 'ದಯವಿಟ್ಟು ಡ್ರಾಪ್‌ಡೌನ್‌ನಿಂದ ಒಂದು ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ.',
      'ko': '드롭다운에서 옵션을 선택하세요',
      'mr': 'कृपया ड्रॉपडाउनमधून एक पर्याय निवडा.',
      'pt': 'Por favor, escolha uma opção no menu suspenso',
      'ro': 'Vă rugăm să alegeți o opțiune din meniul derulant',
      'ru': 'Пожалуйста, выберите вариант из выпадающего списка',
      'ta':
          'கீழ்தோன்றும் பட்டியலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்.',
      'te': 'దయచేసి డ్రాప్‌డౌన్ నుండి ఒక ఎంపికను ఎంచుకోండి.',
      'zh_Hans': '请从下拉菜单中选择一个选项',
    },
    'ryk5f52f': {
      'en': 'Sign up',
      'bn': 'সাইন আপ করুন',
      'de': 'Melden Sie sich an',
      'es': 'Inscribirse',
      'fr': 'S\'inscrire',
      'hi': 'साइन अप करें',
      'ja': 'サインアップ',
      'kn': 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
      'ko': '가입하기',
      'mr': 'साइन अप करा',
      'pt': 'Inscrever-se',
      'ro': 'Înscrie-te',
      'ru': 'Зарегистрироваться',
      'ta': 'பதிவு செய்யவும்',
      'te': 'సైన్ అప్ చేయండి',
      'zh_Hans': '报名',
    },
    'xlya9s4u': {
      'en': 'Sign up with Google',
      'bn': 'গুগলে সাইন আপ করুন',
      'de': 'Mit Google anmelden',
      'es': 'Regístrate con Google',
      'fr': 'Inscrivez-vous avec Google',
      'hi': 'गूगल के साथ साइन अप करें',
      'ja': 'Googleでサインアップ',
      'kn': 'Google ನೊಂದಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
      'ko': 'Google로 가입하세요',
      'mr': 'गुगलसह साइन अप करा',
      'pt': 'Cadastre-se com o Google',
      'ro': 'Înregistrează-te cu Google',
      'ru': 'Зарегистрироваться через Google',
      'ta': 'கூகிள் மூலம் பதிவு செய்யவும்',
      'te': 'Google తో సైన్ అప్ చేయండి',
      'zh_Hans': '使用 Google 注册',
    },
    'i7hw7fwk': {
      'en': 'Already have an account? ',
      'bn': 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
      'de': 'Hast du schon ein Konto?',
      'es': '¿Ya tienes una cuenta?',
      'fr': 'Vous avez déjà un compte ?',
      'hi': 'क्या आपके पास पहले से एक खाता मौजूद है?',
      'ja': 'すでにアカウントをお持ちですか?',
      'kn': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
      'ko': '이미 계정이 있으신가요?',
      'mr': 'आधीपासूनच खाते आहे?',
      'pt': 'Já tem uma conta?',
      'ro': 'Ai deja un cont?',
      'ru': 'У вас уже есть аккаунт?',
      'ta': 'ஏற்கனவே ஒரு கணக்கு உள்ளதா?',
      'te': 'ఖాతా ఉందా?',
      'zh_Hans': '已有账户？',
    },
    'vbdzhu88': {
      'en': 'Sign in',
      'bn': 'প্রবেশ কর',
      'de': 'anmelden',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'hi': 'दाखिल करना',
      'ja': 'サインイン',
      'kn': 'ಸೈನ್ ಇನ್',
      'ko': '로그인',
      'mr': 'भाषा',
      'pt': 'Entrar',
      'ro': 'Conectare',
      'ru': 'Войти',
      'ta': 'உள்நுழையவும்',
      'te': 'సైన్ ఇన్',
      'zh_Hans': '登入',
    },
    'vdmitllc': {
      'en': 'Home',
      'bn': 'হোম',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'kn': 'ಮರಳಿ ಪ್ರಥಮ ಪುಟಕ್ಕೆ',
      'ko': '집',
      'mr': 'मुखपृष्ठ',
      'pt': 'Lar',
      'ro': 'Acasă',
      'ru': 'Дом',
      'ta': 'முகப்புப் பக்கம்',
      'te': 'హొమ్ పేజ్',
      'zh_Hans': '家',
    },
  },
  // Login
  {
    '2ym4kmul': {
      'en': 'Welcome back',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'h6nu2jcs': {
      'en': 'Welcome back! Please enter your details.',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'y8l4gyv2': {
      'en': 'Email',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'pfwxv54x': {
      'en': 'Enter your email',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '7iw5akfn': {
      'en': 'Password',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'vpjo3tcu': {
      'en': '••••••••',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'dn3r62tm': {
      'en': 'Email is required.',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'uomlmjb2': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    's60p5wbl': {
      'en': 'Password is required.',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'k0iaos8a': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'vxl7hzqn': {
      'en': 'Forget password?',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'g6h75zvg': {
      'en': 'Log in',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '8hnop2bs': {
      'en': 'Sign in with Google',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'gycfdo93': {
      'en': 'Don\'t have an account? ',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'trbiagvu': {
      'en': 'Sign up',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ekwpk58w': {
      'en': 'Home',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // EditProfile
  {
    'uhqcy00b': {
      'en': 'Edit your Profile',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '935luji1': {
      'en': 'Your Name',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '87dyt0fg': {
      'en': 'Your bio',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '63oc9zwt': {
      'en': 'Save Changes',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // CreateEventPage
  {
    'hx95pplf': {
      'en': 'Create Event',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '4w4cbqnm': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '2b9u19wh': {
      'en': 'Select a template',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'omwcwc29': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // ChangePassword
  {
    '8bw269za': {
      'en': 'Change Your Password',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '5rw6m1rq': {
      'en': 'New Password',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'lz1788yv': {
      'en': 'Confirm New Password',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'nf8mft8x': {
      'en': 'Change Password',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ehbfqgg7': {
      'en': 'Current Password is required',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '1nk28khi': {
      'en': 'Enter Atleast 6 Characters',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '1hy3wp76': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'qe3oxfue': {
      'en': 'Please enter your new password',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ce1pjli8': {
      'en': 'Enter atleast 6 characters',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'uxysayrz': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'z2b21zkx': {
      'en': 'Please enter confirm password',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'pq2gw9p4': {
      'en': 'Enter atleast 6 characters',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'smsdg2kk': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // SuggestFeature
  {
    'v0m3hkbj': {
      'en': 'Suggest a Feature',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '8id5ijag': {
      'en': 'Describe your feature suggestion',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '9dm1cxco': {
      'en': 'Submit',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'oeemc92a': {
      'en': 'Please enter the bug to report',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'jhgceh6l': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // PreviewPage
  {
    'clvmrgnq': {
      'en': 'Preview',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'hia6pcs1': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'neplmi7y': {
      'en': ' - ',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '8bqlq3ct': {
      'en': 'Event Description',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '73mqvhzf': {
      'en': 'Create Event',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '4zdjsoof': {
      'en': 'Home',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // EnterEventDetails
  {
    'm9bdvwza': {
      'en': 'Event Details ',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '04av7gjl': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '6ltwe34r': {
      'en': 'Event Title',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'v9d9ovxh': {
      'en': 'Enter event title',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'fhdu7hz3': {
      'en': 'Event Type',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '30cohg3f': {
      'en': 'Select event type',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'njdcnm5y': {
      'en': 'Search...',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '67fpg162': {
      'en': 'Birthday',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'v3wyu49x': {
      'en': 'Reunion',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'hbhvagbq': {
      'en': 'Wedding',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ox1wl1y8': {
      'en': 'Party',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '38trg1s9': {
      'en': 'Concert',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '0ianrifz': {
      'en': 'Conference',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '6nu2p3sb': {
      'en': 'Workshop',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'f8aok4l1': {
      'en': 'Webinar',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'drdm5dcx': {
      'en': 'Meetup',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'd3617g8b': {
      'en': 'Sports',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'tfi9wwbn': {
      'en': 'Networking Event',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'z2s3ogk0': {
      'en': 'Charity Event',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'j0medtms': {
      'en': 'Exhibition',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '350emb25': {
      'en': 'Event Description',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'l0ny5sie': {
      'en': 'Write your event description',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '1r3ub9rm': {
      'en': 'Event Timing',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '3r1k74he': {
      'en': 'Location',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '3rlg3kx0': {
      'en': 'Location',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '151t5an8': {
      'en': 'Next: Preview',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '59e50ysk': {
      'en': 'Enter event title is required',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'w03zw380': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '9x943pex': {
      'en': 'Write your event description is required',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '7t00fypr': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'wrvkc18z': {
      'en': 'Start Date is required',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'a6zmlpq3': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'sx1xy6mo': {
      'en': 'End Date is required',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'qpzq8du4': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'mwqacjn7': {
      'en': 'Location is required',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'soc5wo9u': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '2z1e0e65': {
      'en': 'Home',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // CustomizeTemplatePage
  {
    '3f84kxa7': {
      'en': 'Customize Template',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'qtg30ozb': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    't2i87ms8': {
      'en': 'Enter Header Text Here',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '6cyca5wg': {
      'en': 'Enter Body Text Here',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'a5p82gho': {
      'en': 'Enter Footer Text Here',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'oea4yo1o': {
      'en': 'Please enter the header text',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '11650yzf': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'fkewszib': {
      'en': 'Please enter the body text',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '8eumpxd2': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'olx1ko1d': {
      'en': 'Please enter the footer text',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'x6gx0jbp': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'toexrit8': {
      'en': 'Next: Event Details',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'uv1dy6o4': {
      'en': 'Home',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // Discover
  {
    'qr0a4xdk': {
      'en': 'Discover',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'nkrw9ce5': {
      'en': 'Discover',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // ProfilePage
  {
    'fkysb1sf': {
      'en': 'Events Managed',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '2cfu3nzv': {
      'en': '\$0',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '1jarz6ym': {
      'en': 'Money Earned',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'bhdg2p3q': {
      'en': 'My Account Information',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'aqco5g10': {
      'en': 'Change Password',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'c95roj9a': {
      'en': 'Edit Profile',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'mihqsd5r': {
      'en': 'Support',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ua3x081i': {
      'en': 'Tutorial',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'orehns4e': {
      'en': 'Submit a Bug',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'g0jyq0lr': {
      'en': 'Submit a Feature Request',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'evpbgb8s': {
      'en': 'Light ',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'okyo518u': {
      'en': 'Dark',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'wvdqvhah': {
      'en': 'Log Out',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '2w918uk3': {
      'en': 'Profile',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // SubmitBug
  {
    'f9950g0p': {
      'en': 'Report a Bug',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'h54z8ugo': {
      'en': 'Please describe the bug you faced',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'hyeisie6': {
      'en': 'Report',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ka4yqb7g': {
      'en': 'Please enter the bug to report',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'vfmoz598': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // EventsHome
  {
    'bjlf7vkm': {
      'en': 'My Events',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'u15xcb3h': {
      'en': 'RSVP\'s',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'wxg8unhc': {
      'en': 'Events',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // EventDetails
  {
    'jnpjllgp': {
      'en': 'Edit Event',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '1ph55wic': {
      'en': 'Delete Event',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '7co9egy0': {
      'en': 'Event Managed By:-',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'nsw53u6k': {
      'en': 'People attending this event:-',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ciurq64x': {
      'en': 'Home',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // Search
  {
    'v3z18gdt': {
      'en': 'Search events',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'rslfzdw6': {
      'en': 'Search for events...',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'u6fv6efj': {
      'en': 'Events matching search',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'mvh3bukw': {
      'en': 'Home',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // SideBar
  {
    'k2m6891j': {
      'en': 'Eventure',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'x4z5i3k0': {
      'en': 'Home',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ooby0x3t': {
      'en': 'Events',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'suod6uol': {
      'en': 'Profile',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'yrrb35nm': {
      'en': 'Light Mode',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'dpovp3zm': {
      'en': 'Dark Mode',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // AccountUserDropdown
  {
    'iq7armu3': {
      'en': 'Account Options',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'msshlin4': {
      'en': 'My Account',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'mf325jcr': {
      'en': 'Light Mode',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'f615ma5t': {
      'en': 'Dark Mode',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ycrl5iv6': {
      'en': 'Log out',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // FilterDropdown
  {
    'xe7p9xkn': {
      'en': 'Filters',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'b38gz6g5': {
      'en': 'Birthday',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'whfak749': {
      'en': 'Party',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    's8jq3z3s': {
      'en': 'Reunion',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'kmxtqlab': {
      'en': 'Wedding',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'reefe3vu': {
      'en': 'Concert',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'rfff1m5g': {
      'en': 'Conference',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'g6k3xp1n': {
      'en': 'Workshop',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '35luqa4n': {
      'en': 'Webinar',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'kd0fhh34': {
      'en': 'Meetup',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'pvesjth2': {
      'en': 'Sports',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'kyc9ko09': {
      'en': 'Networking Event',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'l8bw61gw': {
      'en': 'Charity',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '3bayyb30': {
      'en': 'Exhibition',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'stlesh35': {
      'en': 'Clear',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // TemplateCard
  {
    'tgdhsk15': {
      'en': 'Royal Wedding Invite',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'b6g35f99': {
      'en': 'Retro Peacock',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'vge2hr7p': {
      'en': 'Casual Wedding',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'tfr6cwin': {
      'en': 'Blue Birthday Party',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    'zveht8kb': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'vhof2mxa': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'htb8b3ne': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '2jay3aoa': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'p5wqn062': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'ugawcda4': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'pau389zq': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'jq4rs5sp': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'emm5hkbg': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'mdcvxgkj': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'jpg63big': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'svg22w8t': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'at1jtqwp': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'owly3h3v': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '5v154y6i': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '884y49hw': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'mg3gdcq4': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'u4ob2wjq': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '56owgg8o': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'qjpuevmy': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'p3gniviw': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '3ilub12i': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '7krqy8vp': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    't7zovtnj': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    '22anagnp': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'frgbntxk': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
    'c22de6xp': {
      'en': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'kn': '',
      'ko': '',
      'mr': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
